### PR TITLE
Limit confirmation dialog to once per hostname, add option to squelch

### PR DESCRIPTION
**Pull request by ajbenton**
Adding an options page to squelch the confirm access prompt.

When not squelched the confirmation prompt will only show once per hostname. The options page has the ability to remove the stored state and the confirmation prompt will come back for all previously acknowledged hostnames.

Removed dependency on Visual Studio and NuGet in favor of a node/npm build.

### CODE REVIEW

**Comment by ajbenton** [comment]
This should resolve issue #1

**Comment by ajbenton** [comment]
Awesome. @itsmikeeng Don't suppose you could publish the new version as well?

**Comment by itsmikeeng** [comment]
Sure I will publish tonight.

**Comment by ajbenton** [comment]
👍 🍻 💯

**Pull request merged**
